version: 1.0.{build}

platform:
  - x64
  
build_script:
  - ps: >-
      ./newrelic-dotnet.ps1;
      choco pack output/newrelic-dotnet.nuspec

test_script:
  - ps: cinst newrelic-dotnet -fdvy -source "$pwd;http://chocolatey.org/api/v2/"
  - ps: cuninst -fdvy newrelic-dotnet
  - ps: cinst newrelic-dotnet -fdvy --x86 -source "$pwd;http://chocolatey.org/api/v2/"
  - ps: cuninst -fdvy newrelic-dotnet 

artifacts:
  - path: '**\*.nupkg'